// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pt_room/room.proto

package pt_room

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pt_com "../pt_com"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type T2RTableLogin struct {
	Item                 *pt_com.RoomTableItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *T2RTableLogin) Reset()         { *m = T2RTableLogin{} }
func (m *T2RTableLogin) String() string { return proto.CompactTextString(m) }
func (*T2RTableLogin) ProtoMessage()    {}
func (*T2RTableLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae60e262f4b1c9, []int{0}
}

func (m *T2RTableLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_T2RTableLogin.Unmarshal(m, b)
}
func (m *T2RTableLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_T2RTableLogin.Marshal(b, m, deterministic)
}
func (m *T2RTableLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_T2RTableLogin.Merge(m, src)
}
func (m *T2RTableLogin) XXX_Size() int {
	return xxx_messageInfo_T2RTableLogin.Size(m)
}
func (m *T2RTableLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_T2RTableLogin.DiscardUnknown(m)
}

var xxx_messageInfo_T2RTableLogin proto.InternalMessageInfo

func (m *T2RTableLogin) GetItem() *pt_com.RoomTableItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type R2TTableLoginResult struct {
	Code                 int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Item                 *pt_com.RoomTableItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *R2TTableLoginResult) Reset()         { *m = R2TTableLoginResult{} }
func (m *R2TTableLoginResult) String() string { return proto.CompactTextString(m) }
func (*R2TTableLoginResult) ProtoMessage()    {}
func (*R2TTableLoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae60e262f4b1c9, []int{1}
}

func (m *R2TTableLoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2TTableLoginResult.Unmarshal(m, b)
}
func (m *R2TTableLoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2TTableLoginResult.Marshal(b, m, deterministic)
}
func (m *R2TTableLoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2TTableLoginResult.Merge(m, src)
}
func (m *R2TTableLoginResult) XXX_Size() int {
	return xxx_messageInfo_R2TTableLoginResult.Size(m)
}
func (m *R2TTableLoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_R2TTableLoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_R2TTableLoginResult proto.InternalMessageInfo

func (m *R2TTableLoginResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *R2TTableLoginResult) GetItem() *pt_com.RoomTableItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type R2TRoomUserSitdown struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Chairid              uint32   `protobuf:"varint,2,opt,name=chairid,proto3" json:"chairid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *R2TRoomUserSitdown) Reset()         { *m = R2TRoomUserSitdown{} }
func (m *R2TRoomUserSitdown) String() string { return proto.CompactTextString(m) }
func (*R2TRoomUserSitdown) ProtoMessage()    {}
func (*R2TRoomUserSitdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae60e262f4b1c9, []int{2}
}

func (m *R2TRoomUserSitdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2TRoomUserSitdown.Unmarshal(m, b)
}
func (m *R2TRoomUserSitdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2TRoomUserSitdown.Marshal(b, m, deterministic)
}
func (m *R2TRoomUserSitdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2TRoomUserSitdown.Merge(m, src)
}
func (m *R2TRoomUserSitdown) XXX_Size() int {
	return xxx_messageInfo_R2TRoomUserSitdown.Size(m)
}
func (m *R2TRoomUserSitdown) XXX_DiscardUnknown() {
	xxx_messageInfo_R2TRoomUserSitdown.DiscardUnknown(m)
}

var xxx_messageInfo_R2TRoomUserSitdown proto.InternalMessageInfo

func (m *R2TRoomUserSitdown) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *R2TRoomUserSitdown) GetChairid() uint32 {
	if m != nil {
		return m.Chairid
	}
	return 0
}

type R2TRoomUserStandup struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *R2TRoomUserStandup) Reset()         { *m = R2TRoomUserStandup{} }
func (m *R2TRoomUserStandup) String() string { return proto.CompactTextString(m) }
func (*R2TRoomUserStandup) ProtoMessage()    {}
func (*R2TRoomUserStandup) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ae60e262f4b1c9, []int{3}
}

func (m *R2TRoomUserStandup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2TRoomUserStandup.Unmarshal(m, b)
}
func (m *R2TRoomUserStandup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2TRoomUserStandup.Marshal(b, m, deterministic)
}
func (m *R2TRoomUserStandup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2TRoomUserStandup.Merge(m, src)
}
func (m *R2TRoomUserStandup) XXX_Size() int {
	return xxx_messageInfo_R2TRoomUserStandup.Size(m)
}
func (m *R2TRoomUserStandup) XXX_DiscardUnknown() {
	xxx_messageInfo_R2TRoomUserStandup.DiscardUnknown(m)
}

var xxx_messageInfo_R2TRoomUserStandup proto.InternalMessageInfo

func (m *R2TRoomUserStandup) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func init() {
	proto.RegisterType((*T2RTableLogin)(nil), "pt_room.t2r_table_login")
	proto.RegisterType((*R2TTableLoginResult)(nil), "pt_room.r2t_table_login_result")
	proto.RegisterType((*R2TRoomUserSitdown)(nil), "pt_room.r2t_room_user_sitdown")
	proto.RegisterType((*R2TRoomUserStandup)(nil), "pt_room.r2t_room_user_standup")
}

func init() { proto.RegisterFile("pt_room/room.proto", fileDescriptor_27ae60e262f4b1c9) }

var fileDescriptor_27ae60e262f4b1c9 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x71, 0x6d, 0xb8, 0x52, 0x0a, 0x2a, 0x75, 0x4d, 0xa7, 0xe2, 0xa9, 0x50, 0xb0,
	0xc1, 0xdd, 0xbb, 0x77, 0xd5, 0xd6, 0x49, 0xd8, 0x92, 0x48, 0x04, 0x96, 0x4e, 0xc8, 0x67, 0xf2,
	0xf7, 0x83, 0x64, 0x27, 0x04, 0x42, 0x20, 0x8b, 0xd0, 0xd3, 0x77, 0xef, 0x13, 0x1c, 0x30, 0x4f,
	0x22, 0x20, 0xda, 0x2e, 0x1e, 0xad, 0x0f, 0x48, 0xc8, 0xca, 0xed, 0xed, 0xe3, 0xd5, 0x93, 0x90,
	0x68, 0x3b, 0x89, 0xd6, 0xa2, 0x5b, 0x69, 0xf3, 0x0b, 0x2f, 0xd4, 0x07, 0x41, 0xc3, 0x38, 0x69,
	0x31, 0xe1, 0xce, 0x38, 0xf6, 0x0d, 0xb9, 0x21, 0x6d, 0xeb, 0xec, 0x33, 0xfb, 0x7a, 0xea, 0xdf,
	0xdb, 0xb5, 0xd6, 0x46, 0xc7, 0x36, 0x17, 0x31, 0x4f, 0x43, 0xcd, 0x3f, 0x54, 0xa1, 0xa7, 0xcb,
	0xbe, 0x08, 0x7a, 0x5e, 0x26, 0x62, 0x0c, 0x72, 0x89, 0x4a, 0x27, 0xcd, 0x23, 0x4f, 0xf7, 0xb3,
	0xfa, 0xe1, 0x1e, 0xf5, 0x1f, 0xbc, 0x45, 0x75, 0x82, 0xcb, 0xac, 0x83, 0x98, 0x0d, 0x29, 0x3c,
	0x38, 0x56, 0x41, 0x11, 0xb3, 0x51, 0xc9, 0x9d, 0xf3, 0x2d, 0xb1, 0x1a, 0x4a, 0xb9, 0x1f, 0x4c,
	0x04, 0xf1, 0x83, 0x67, 0x7e, 0x8a, 0x4d, 0x77, 0xa5, 0xa2, 0xc1, 0xa9, 0xc5, 0xdf, 0x52, 0x8d,
	0x45, 0xda, 0xce, 0xcf, 0x31, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xca, 0x49, 0xb3, 0x51, 0x01, 0x00,
	0x00,
}
