// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pt_com/common.proto

package pt_com

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ComPid int32

const (
	ComPid_COM_NONE          ComPid = 0
	ComPid_COM_REGISTER_NODE ComPid = 1
)

var ComPid_name = map[int32]string{
	0: "COM_NONE",
	1: "COM_REGISTER_NODE",
}

var ComPid_value = map[string]int32{
	"COM_NONE":          0,
	"COM_REGISTER_NODE": 1,
}

func (x ComPid) String() string {
	return proto.EnumName(ComPid_name, int32(x))
}

func (ComPid) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{0}
}

type NodeType int32

const (
	NodeType_NODE_UNKNOW       NodeType = 0
	NodeType_NODE_LOGIN_SERVER NodeType = 1
	NodeType_NODE_ROOM_SERVER  NodeType = 2
)

var NodeType_name = map[int32]string{
	0: "NODE_UNKNOW",
	1: "NODE_LOGIN_SERVER",
	2: "NODE_ROOM_SERVER",
}

var NodeType_value = map[string]int32{
	"NODE_UNKNOW":       0,
	"NODE_LOGIN_SERVER": 1,
	"NODE_ROOM_SERVER":  2,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{1}
}

type RoomItem struct {
	Roomid               uint64   `protobuf:"varint,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Roomname             string   `protobuf:"bytes,2,opt,name=roomname,proto3" json:"roomname,omitempty"`
	Roomkind             uint32   `protobuf:"varint,3,opt,name=roomkind,proto3" json:"roomkind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomItem) Reset()         { *m = RoomItem{} }
func (m *RoomItem) String() string { return proto.CompactTextString(m) }
func (*RoomItem) ProtoMessage()    {}
func (*RoomItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{0}
}

func (m *RoomItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomItem.Unmarshal(m, b)
}
func (m *RoomItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomItem.Marshal(b, m, deterministic)
}
func (m *RoomItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomItem.Merge(m, src)
}
func (m *RoomItem) XXX_Size() int {
	return xxx_messageInfo_RoomItem.Size(m)
}
func (m *RoomItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomItem.DiscardUnknown(m)
}

var xxx_messageInfo_RoomItem proto.InternalMessageInfo

func (m *RoomItem) GetRoomid() uint64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *RoomItem) GetRoomname() string {
	if m != nil {
		return m.Roomname
	}
	return ""
}

func (m *RoomItem) GetRoomkind() uint32 {
	if m != nil {
		return m.Roomkind
	}
	return 0
}

type RoomUserItem struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gold                 uint64   `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	Tableid              uint32   `protobuf:"varint,4,opt,name=tableid,proto3" json:"tableid,omitempty"`
	Chairid              uint32   `protobuf:"varint,5,opt,name=chairid,proto3" json:"chairid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomUserItem) Reset()         { *m = RoomUserItem{} }
func (m *RoomUserItem) String() string { return proto.CompactTextString(m) }
func (*RoomUserItem) ProtoMessage()    {}
func (*RoomUserItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{1}
}

func (m *RoomUserItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUserItem.Unmarshal(m, b)
}
func (m *RoomUserItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUserItem.Marshal(b, m, deterministic)
}
func (m *RoomUserItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUserItem.Merge(m, src)
}
func (m *RoomUserItem) XXX_Size() int {
	return xxx_messageInfo_RoomUserItem.Size(m)
}
func (m *RoomUserItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUserItem.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUserItem proto.InternalMessageInfo

func (m *RoomUserItem) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *RoomUserItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomUserItem) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *RoomUserItem) GetTableid() uint32 {
	if m != nil {
		return m.Tableid
	}
	return 0
}

func (m *RoomUserItem) GetChairid() uint32 {
	if m != nil {
		return m.Chairid
	}
	return 0
}

type RoomTableItem struct {
	Tableid              uint32   `protobuf:"varint,1,opt,name=tableid,proto3" json:"tableid,omitempty"`
	Capacity             uint32   `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomTableItem) Reset()         { *m = RoomTableItem{} }
func (m *RoomTableItem) String() string { return proto.CompactTextString(m) }
func (*RoomTableItem) ProtoMessage()    {}
func (*RoomTableItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{2}
}

func (m *RoomTableItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomTableItem.Unmarshal(m, b)
}
func (m *RoomTableItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomTableItem.Marshal(b, m, deterministic)
}
func (m *RoomTableItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomTableItem.Merge(m, src)
}
func (m *RoomTableItem) XXX_Size() int {
	return xxx_messageInfo_RoomTableItem.Size(m)
}
func (m *RoomTableItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomTableItem.DiscardUnknown(m)
}

var xxx_messageInfo_RoomTableItem proto.InternalMessageInfo

func (m *RoomTableItem) GetTableid() uint32 {
	if m != nil {
		return m.Tableid
	}
	return 0
}

func (m *RoomTableItem) GetCapacity() uint32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type C2SRegisterNode struct {
	Nodetype             uint32   `protobuf:"varint,1,opt,name=nodetype,proto3" json:"nodetype,omitempty"`
	Extra                *any.Any `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SRegisterNode) Reset()         { *m = C2SRegisterNode{} }
func (m *C2SRegisterNode) String() string { return proto.CompactTextString(m) }
func (*C2SRegisterNode) ProtoMessage()    {}
func (*C2SRegisterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{3}
}

func (m *C2SRegisterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SRegisterNode.Unmarshal(m, b)
}
func (m *C2SRegisterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SRegisterNode.Marshal(b, m, deterministic)
}
func (m *C2SRegisterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SRegisterNode.Merge(m, src)
}
func (m *C2SRegisterNode) XXX_Size() int {
	return xxx_messageInfo_C2SRegisterNode.Size(m)
}
func (m *C2SRegisterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SRegisterNode.DiscardUnknown(m)
}

var xxx_messageInfo_C2SRegisterNode proto.InternalMessageInfo

func (m *C2SRegisterNode) GetNodetype() uint32 {
	if m != nil {
		return m.Nodetype
	}
	return 0
}

func (m *C2SRegisterNode) GetExtra() *any.Any {
	if m != nil {
		return m.Extra
	}
	return nil
}

type S2CRegisterNodeResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Nodetype             uint32   `protobuf:"varint,2,opt,name=nodetype,proto3" json:"nodetype,omitempty"`
	Extra                *any.Any `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRegisterNodeResult) Reset()         { *m = S2CRegisterNodeResult{} }
func (m *S2CRegisterNodeResult) String() string { return proto.CompactTextString(m) }
func (*S2CRegisterNodeResult) ProtoMessage()    {}
func (*S2CRegisterNodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8102e54e31483ac2, []int{4}
}

func (m *S2CRegisterNodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRegisterNodeResult.Unmarshal(m, b)
}
func (m *S2CRegisterNodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRegisterNodeResult.Marshal(b, m, deterministic)
}
func (m *S2CRegisterNodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRegisterNodeResult.Merge(m, src)
}
func (m *S2CRegisterNodeResult) XXX_Size() int {
	return xxx_messageInfo_S2CRegisterNodeResult.Size(m)
}
func (m *S2CRegisterNodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRegisterNodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRegisterNodeResult proto.InternalMessageInfo

func (m *S2CRegisterNodeResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *S2CRegisterNodeResult) GetNodetype() uint32 {
	if m != nil {
		return m.Nodetype
	}
	return 0
}

func (m *S2CRegisterNodeResult) GetExtra() *any.Any {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterEnum("pt_com.ComPid", ComPid_name, ComPid_value)
	proto.RegisterEnum("pt_com.NodeType", NodeType_name, NodeType_value)
	proto.RegisterType((*RoomItem)(nil), "pt_com.room_item")
	proto.RegisterType((*RoomUserItem)(nil), "pt_com.room_user_item")
	proto.RegisterType((*RoomTableItem)(nil), "pt_com.room_table_item")
	proto.RegisterType((*C2SRegisterNode)(nil), "pt_com.c2s_register_node")
	proto.RegisterType((*S2CRegisterNodeResult)(nil), "pt_com.s2c_register_node_result")
}

func init() { proto.RegisterFile("pt_com/common.proto", fileDescriptor_8102e54e31483ac2) }

var fileDescriptor_8102e54e31483ac2 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x71, 0xb7, 0xed, 0xb6, 0xb3, 0x2c, 0xdb, 0x35, 0x0b, 0x0a, 0x3d, 0x55, 0x39, 0x55,
	0x3d, 0xa4, 0x52, 0xf9, 0x04, 0x08, 0xa2, 0xaa, 0x82, 0x4d, 0x24, 0x2f, 0x7f, 0x0e, 0x7b, 0xb0,
	0x52, 0xc7, 0x04, 0x8b, 0x24, 0x8e, 0x12, 0x17, 0x91, 0x3b, 0x1f, 0x1c, 0x79, 0xdc, 0x84, 0xf6,
	0x80, 0xf6, 0x94, 0xf9, 0x3d, 0x4f, 0xde, 0x7b, 0xb2, 0xe1, 0x65, 0x65, 0xb8, 0xd0, 0xc5, 0x5a,
	0xe8, 0xa2, 0xd0, 0x65, 0x50, 0xd5, 0xda, 0x68, 0x3a, 0x76, 0xe2, 0xfc, 0x4d, 0xa6, 0x75, 0x96,
	0xcb, 0x35, 0xaa, 0xfb, 0xc3, 0xf7, 0x75, 0x52, 0xb6, 0x6e, 0xc5, 0x7f, 0x84, 0x69, 0xad, 0x75,
	0xc1, 0x95, 0x91, 0x05, 0x7d, 0x0d, 0x63, 0x0b, 0x2a, 0xf5, 0xc8, 0x82, 0x2c, 0x87, 0xec, 0x48,
	0x74, 0x0e, 0x13, 0x3b, 0x95, 0x49, 0x21, 0xbd, 0xc1, 0x82, 0x2c, 0xa7, 0xac, 0xe7, 0xee, 0xec,
	0xa7, 0x2a, 0x53, 0xef, 0x62, 0x41, 0x96, 0xd7, 0xac, 0x67, 0xff, 0x0f, 0x81, 0x17, 0xe8, 0x7e,
	0x68, 0x64, 0xdd, 0x47, 0x58, 0xf8, 0x17, 0xe1, 0x88, 0x52, 0x18, 0x9e, 0xd8, 0xe3, 0x6c, 0xb5,
	0x4c, 0xe7, 0xce, 0x76, 0xc8, 0x70, 0xa6, 0x1e, 0x5c, 0x9a, 0x64, 0x9f, 0x4b, 0x95, 0x7a, 0x43,
	0x4c, 0xeb, 0xd0, 0x9e, 0x88, 0x1f, 0x89, 0xb2, 0xd6, 0x23, 0x77, 0x72, 0x44, 0x7f, 0x0b, 0x37,
	0xd8, 0x02, 0x37, 0x5d, 0x8d, 0x13, 0x1b, 0x72, 0x6e, 0x33, 0x87, 0x89, 0x48, 0xaa, 0x44, 0x28,
	0xd3, 0x62, 0x99, 0x6b, 0xd6, 0xb3, 0xff, 0x08, 0xb7, 0x62, 0xd3, 0xf0, 0x5a, 0x66, 0xaa, 0x31,
	0xb2, 0xe6, 0xa5, 0x4e, 0xf1, 0x02, 0xec, 0xd7, 0xb4, 0x95, 0x3c, 0x7a, 0xf5, 0x4c, 0x57, 0x30,
	0x92, 0xbf, 0x4d, 0x9d, 0xa0, 0xd3, 0xd5, 0xe6, 0x2e, 0x70, 0x0f, 0x11, 0x74, 0x0f, 0x11, 0xbc,
	0x2b, 0x5b, 0xe6, 0x56, 0xfc, 0x5f, 0xe0, 0x35, 0x1b, 0x71, 0x6e, 0xce, 0x6b, 0xd9, 0x1c, 0x72,
	0x63, 0x6f, 0x42, 0xe8, 0xd4, 0xf9, 0x8f, 0x18, 0xce, 0x67, 0xb9, 0x83, 0xff, 0xe5, 0x5e, 0x3c,
	0x99, 0xbb, 0x0a, 0xe0, 0x52, 0xe8, 0x82, 0x57, 0x2a, 0xa5, 0xcf, 0x61, 0xf2, 0x3e, 0xbe, 0xe7,
	0x51, 0x1c, 0x85, 0xb3, 0x67, 0xf4, 0x15, 0xdc, 0x5a, 0x62, 0xe1, 0x76, 0xf7, 0xf0, 0x39, 0x64,
	0x3c, 0x8a, 0x3f, 0x84, 0x33, 0xb2, 0xda, 0xc1, 0x14, 0xab, 0x61, 0xd0, 0x0d, 0x5c, 0x59, 0x99,
	0x7f, 0x89, 0x3e, 0x46, 0xf1, 0x37, 0xf7, 0x13, 0x0a, 0x9f, 0xe2, 0xed, 0x2e, 0xe2, 0x0f, 0x21,
	0xfb, 0x1a, 0xb2, 0x19, 0xa1, 0x77, 0x30, 0x43, 0x99, 0xc5, 0xf1, 0x7d, 0xa7, 0x0e, 0xf6, 0x63,
	0xec, 0xf3, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x1b, 0x11, 0x39, 0xbd, 0x02, 0x00,
	0x00,
}
