// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pt_logical/room.proto

package pt_logical

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pt_com "../pt_com"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type S2LRoomUserEnter struct {
	Loginsocket          uint32   `protobuf:"varint,1,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Roomid               uint64   `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2LRoomUserEnter) Reset()         { *m = S2LRoomUserEnter{} }
func (m *S2LRoomUserEnter) String() string { return proto.CompactTextString(m) }
func (*S2LRoomUserEnter) ProtoMessage()    {}
func (*S2LRoomUserEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{0}
}

func (m *S2LRoomUserEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2LRoomUserEnter.Unmarshal(m, b)
}
func (m *S2LRoomUserEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2LRoomUserEnter.Marshal(b, m, deterministic)
}
func (m *S2LRoomUserEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2LRoomUserEnter.Merge(m, src)
}
func (m *S2LRoomUserEnter) XXX_Size() int {
	return xxx_messageInfo_S2LRoomUserEnter.Size(m)
}
func (m *S2LRoomUserEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_S2LRoomUserEnter.DiscardUnknown(m)
}

var xxx_messageInfo_S2LRoomUserEnter proto.InternalMessageInfo

func (m *S2LRoomUserEnter) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *S2LRoomUserEnter) GetRoomid() uint64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

type L2SRoomUserEnterResult struct {
	Loginsocket          uint32                           `protobuf:"varint,1,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Code                 int32                            `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Roomid               uint64                           `protobuf:"varint,3,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Users                map[uint64]*pt_com.RoomUserItem  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tables               map[uint32]*pt_com.RoomTableItem `protobuf:"bytes,5,rep,name=tables,proto3" json:"tables,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *L2SRoomUserEnterResult) Reset()         { *m = L2SRoomUserEnterResult{} }
func (m *L2SRoomUserEnterResult) String() string { return proto.CompactTextString(m) }
func (*L2SRoomUserEnterResult) ProtoMessage()    {}
func (*L2SRoomUserEnterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{1}
}

func (m *L2SRoomUserEnterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2SRoomUserEnterResult.Unmarshal(m, b)
}
func (m *L2SRoomUserEnterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2SRoomUserEnterResult.Marshal(b, m, deterministic)
}
func (m *L2SRoomUserEnterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2SRoomUserEnterResult.Merge(m, src)
}
func (m *L2SRoomUserEnterResult) XXX_Size() int {
	return xxx_messageInfo_L2SRoomUserEnterResult.Size(m)
}
func (m *L2SRoomUserEnterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_L2SRoomUserEnterResult.DiscardUnknown(m)
}

var xxx_messageInfo_L2SRoomUserEnterResult proto.InternalMessageInfo

func (m *L2SRoomUserEnterResult) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *L2SRoomUserEnterResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *L2SRoomUserEnterResult) GetRoomid() uint64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *L2SRoomUserEnterResult) GetUsers() map[uint64]*pt_com.RoomUserItem {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *L2SRoomUserEnterResult) GetTables() map[uint32]*pt_com.RoomTableItem {
	if m != nil {
		return m.Tables
	}
	return nil
}

type S2LRoomUserLeave struct {
	Loginsocket          uint32   `protobuf:"varint,1,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2LRoomUserLeave) Reset()         { *m = S2LRoomUserLeave{} }
func (m *S2LRoomUserLeave) String() string { return proto.CompactTextString(m) }
func (*S2LRoomUserLeave) ProtoMessage()    {}
func (*S2LRoomUserLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{2}
}

func (m *S2LRoomUserLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2LRoomUserLeave.Unmarshal(m, b)
}
func (m *S2LRoomUserLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2LRoomUserLeave.Marshal(b, m, deterministic)
}
func (m *S2LRoomUserLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2LRoomUserLeave.Merge(m, src)
}
func (m *S2LRoomUserLeave) XXX_Size() int {
	return xxx_messageInfo_S2LRoomUserLeave.Size(m)
}
func (m *S2LRoomUserLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_S2LRoomUserLeave.DiscardUnknown(m)
}

var xxx_messageInfo_S2LRoomUserLeave proto.InternalMessageInfo

func (m *S2LRoomUserLeave) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

type L2SRoomUserLeaveResult struct {
	Loginsocket          uint32   `protobuf:"varint,1,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Roomid               uint64   `protobuf:"varint,3,opt,name=roomid,proto3" json:"roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2SRoomUserLeaveResult) Reset()         { *m = L2SRoomUserLeaveResult{} }
func (m *L2SRoomUserLeaveResult) String() string { return proto.CompactTextString(m) }
func (*L2SRoomUserLeaveResult) ProtoMessage()    {}
func (*L2SRoomUserLeaveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{3}
}

func (m *L2SRoomUserLeaveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2SRoomUserLeaveResult.Unmarshal(m, b)
}
func (m *L2SRoomUserLeaveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2SRoomUserLeaveResult.Marshal(b, m, deterministic)
}
func (m *L2SRoomUserLeaveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2SRoomUserLeaveResult.Merge(m, src)
}
func (m *L2SRoomUserLeaveResult) XXX_Size() int {
	return xxx_messageInfo_L2SRoomUserLeaveResult.Size(m)
}
func (m *L2SRoomUserLeaveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_L2SRoomUserLeaveResult.DiscardUnknown(m)
}

var xxx_messageInfo_L2SRoomUserLeaveResult proto.InternalMessageInfo

func (m *L2SRoomUserLeaveResult) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *L2SRoomUserLeaveResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *L2SRoomUserLeaveResult) GetRoomid() uint64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

type L2SRoomNotifyAppendUser struct {
	Loginsocket          uint32               `protobuf:"varint,1,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Item                 *pt_com.RoomUserItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *L2SRoomNotifyAppendUser) Reset()         { *m = L2SRoomNotifyAppendUser{} }
func (m *L2SRoomNotifyAppendUser) String() string { return proto.CompactTextString(m) }
func (*L2SRoomNotifyAppendUser) ProtoMessage()    {}
func (*L2SRoomNotifyAppendUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{4}
}

func (m *L2SRoomNotifyAppendUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2SRoomNotifyAppendUser.Unmarshal(m, b)
}
func (m *L2SRoomNotifyAppendUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2SRoomNotifyAppendUser.Marshal(b, m, deterministic)
}
func (m *L2SRoomNotifyAppendUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2SRoomNotifyAppendUser.Merge(m, src)
}
func (m *L2SRoomNotifyAppendUser) XXX_Size() int {
	return xxx_messageInfo_L2SRoomNotifyAppendUser.Size(m)
}
func (m *L2SRoomNotifyAppendUser) XXX_DiscardUnknown() {
	xxx_messageInfo_L2SRoomNotifyAppendUser.DiscardUnknown(m)
}

var xxx_messageInfo_L2SRoomNotifyAppendUser proto.InternalMessageInfo

func (m *L2SRoomNotifyAppendUser) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *L2SRoomNotifyAppendUser) GetItem() *pt_com.RoomUserItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type L2SRoomNotifyRemoveUser struct {
	Loginsocket          uint32   `protobuf:"varint,1,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Userid               uint64   `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2SRoomNotifyRemoveUser) Reset()         { *m = L2SRoomNotifyRemoveUser{} }
func (m *L2SRoomNotifyRemoveUser) String() string { return proto.CompactTextString(m) }
func (*L2SRoomNotifyRemoveUser) ProtoMessage()    {}
func (*L2SRoomNotifyRemoveUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{5}
}

func (m *L2SRoomNotifyRemoveUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2SRoomNotifyRemoveUser.Unmarshal(m, b)
}
func (m *L2SRoomNotifyRemoveUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2SRoomNotifyRemoveUser.Marshal(b, m, deterministic)
}
func (m *L2SRoomNotifyRemoveUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2SRoomNotifyRemoveUser.Merge(m, src)
}
func (m *L2SRoomNotifyRemoveUser) XXX_Size() int {
	return xxx_messageInfo_L2SRoomNotifyRemoveUser.Size(m)
}
func (m *L2SRoomNotifyRemoveUser) XXX_DiscardUnknown() {
	xxx_messageInfo_L2SRoomNotifyRemoveUser.DiscardUnknown(m)
}

var xxx_messageInfo_L2SRoomNotifyRemoveUser proto.InternalMessageInfo

func (m *L2SRoomNotifyRemoveUser) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *L2SRoomNotifyRemoveUser) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type R2LTableLogin struct {
	Tablesocket          uint32                `protobuf:"varint,1,opt,name=tablesocket,proto3" json:"tablesocket,omitempty"`
	Address              string                `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Item                 *pt_com.RoomTableItem `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *R2LTableLogin) Reset()         { *m = R2LTableLogin{} }
func (m *R2LTableLogin) String() string { return proto.CompactTextString(m) }
func (*R2LTableLogin) ProtoMessage()    {}
func (*R2LTableLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{6}
}

func (m *R2LTableLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2LTableLogin.Unmarshal(m, b)
}
func (m *R2LTableLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2LTableLogin.Marshal(b, m, deterministic)
}
func (m *R2LTableLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2LTableLogin.Merge(m, src)
}
func (m *R2LTableLogin) XXX_Size() int {
	return xxx_messageInfo_R2LTableLogin.Size(m)
}
func (m *R2LTableLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_R2LTableLogin.DiscardUnknown(m)
}

var xxx_messageInfo_R2LTableLogin proto.InternalMessageInfo

func (m *R2LTableLogin) GetTablesocket() uint32 {
	if m != nil {
		return m.Tablesocket
	}
	return 0
}

func (m *R2LTableLogin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *R2LTableLogin) GetItem() *pt_com.RoomTableItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type L2RTableLoginResult struct {
	Code                 int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Tablesocket          uint32                `protobuf:"varint,2,opt,name=tablesocket,proto3" json:"tablesocket,omitempty"`
	Address              string                `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Item                 *pt_com.RoomTableItem `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *L2RTableLoginResult) Reset()         { *m = L2RTableLoginResult{} }
func (m *L2RTableLoginResult) String() string { return proto.CompactTextString(m) }
func (*L2RTableLoginResult) ProtoMessage()    {}
func (*L2RTableLoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{7}
}

func (m *L2RTableLoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2RTableLoginResult.Unmarshal(m, b)
}
func (m *L2RTableLoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2RTableLoginResult.Marshal(b, m, deterministic)
}
func (m *L2RTableLoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2RTableLoginResult.Merge(m, src)
}
func (m *L2RTableLoginResult) XXX_Size() int {
	return xxx_messageInfo_L2RTableLoginResult.Size(m)
}
func (m *L2RTableLoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_L2RTableLoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_L2RTableLoginResult proto.InternalMessageInfo

func (m *L2RTableLoginResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *L2RTableLoginResult) GetTablesocket() uint32 {
	if m != nil {
		return m.Tablesocket
	}
	return 0
}

func (m *L2RTableLoginResult) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *L2RTableLoginResult) GetItem() *pt_com.RoomTableItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type R2LTableLost struct {
	Tableid              uint32   `protobuf:"varint,1,opt,name=tableid,proto3" json:"tableid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *R2LTableLost) Reset()         { *m = R2LTableLost{} }
func (m *R2LTableLost) String() string { return proto.CompactTextString(m) }
func (*R2LTableLost) ProtoMessage()    {}
func (*R2LTableLost) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{8}
}

func (m *R2LTableLost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2LTableLost.Unmarshal(m, b)
}
func (m *R2LTableLost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2LTableLost.Marshal(b, m, deterministic)
}
func (m *R2LTableLost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2LTableLost.Merge(m, src)
}
func (m *R2LTableLost) XXX_Size() int {
	return xxx_messageInfo_R2LTableLost.Size(m)
}
func (m *R2LTableLost) XXX_DiscardUnknown() {
	xxx_messageInfo_R2LTableLost.DiscardUnknown(m)
}

var xxx_messageInfo_R2LTableLost proto.InternalMessageInfo

func (m *R2LTableLost) GetTableid() uint32 {
	if m != nil {
		return m.Tableid
	}
	return 0
}

type L2RRoomUserEnter struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2RRoomUserEnter) Reset()         { *m = L2RRoomUserEnter{} }
func (m *L2RRoomUserEnter) String() string { return proto.CompactTextString(m) }
func (*L2RRoomUserEnter) ProtoMessage()    {}
func (*L2RRoomUserEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{9}
}

func (m *L2RRoomUserEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2RRoomUserEnter.Unmarshal(m, b)
}
func (m *L2RRoomUserEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2RRoomUserEnter.Marshal(b, m, deterministic)
}
func (m *L2RRoomUserEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2RRoomUserEnter.Merge(m, src)
}
func (m *L2RRoomUserEnter) XXX_Size() int {
	return xxx_messageInfo_L2RRoomUserEnter.Size(m)
}
func (m *L2RRoomUserEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_L2RRoomUserEnter.DiscardUnknown(m)
}

var xxx_messageInfo_L2RRoomUserEnter proto.InternalMessageInfo

func (m *L2RRoomUserEnter) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type L2RRoomUserLeave struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2RRoomUserLeave) Reset()         { *m = L2RRoomUserLeave{} }
func (m *L2RRoomUserLeave) String() string { return proto.CompactTextString(m) }
func (*L2RRoomUserLeave) ProtoMessage()    {}
func (*L2RRoomUserLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{10}
}

func (m *L2RRoomUserLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2RRoomUserLeave.Unmarshal(m, b)
}
func (m *L2RRoomUserLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2RRoomUserLeave.Marshal(b, m, deterministic)
}
func (m *L2RRoomUserLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2RRoomUserLeave.Merge(m, src)
}
func (m *L2RRoomUserLeave) XXX_Size() int {
	return xxx_messageInfo_L2RRoomUserLeave.Size(m)
}
func (m *L2RRoomUserLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_L2RRoomUserLeave.DiscardUnknown(m)
}

var xxx_messageInfo_L2RRoomUserLeave proto.InternalMessageInfo

func (m *L2RRoomUserLeave) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type L2RRoomUserSitdown struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Tableid              uint32   `protobuf:"varint,2,opt,name=tableid,proto3" json:"tableid,omitempty"`
	Chairid              uint32   `protobuf:"varint,3,opt,name=chairid,proto3" json:"chairid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2RRoomUserSitdown) Reset()         { *m = L2RRoomUserSitdown{} }
func (m *L2RRoomUserSitdown) String() string { return proto.CompactTextString(m) }
func (*L2RRoomUserSitdown) ProtoMessage()    {}
func (*L2RRoomUserSitdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{11}
}

func (m *L2RRoomUserSitdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2RRoomUserSitdown.Unmarshal(m, b)
}
func (m *L2RRoomUserSitdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2RRoomUserSitdown.Marshal(b, m, deterministic)
}
func (m *L2RRoomUserSitdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2RRoomUserSitdown.Merge(m, src)
}
func (m *L2RRoomUserSitdown) XXX_Size() int {
	return xxx_messageInfo_L2RRoomUserSitdown.Size(m)
}
func (m *L2RRoomUserSitdown) XXX_DiscardUnknown() {
	xxx_messageInfo_L2RRoomUserSitdown.DiscardUnknown(m)
}

var xxx_messageInfo_L2RRoomUserSitdown proto.InternalMessageInfo

func (m *L2RRoomUserSitdown) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *L2RRoomUserSitdown) GetTableid() uint32 {
	if m != nil {
		return m.Tableid
	}
	return 0
}

func (m *L2RRoomUserSitdown) GetChairid() uint32 {
	if m != nil {
		return m.Chairid
	}
	return 0
}

type L2RRoomUserStandup struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2RRoomUserStandup) Reset()         { *m = L2RRoomUserStandup{} }
func (m *L2RRoomUserStandup) String() string { return proto.CompactTextString(m) }
func (*L2RRoomUserStandup) ProtoMessage()    {}
func (*L2RRoomUserStandup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddbfd73fe07213aa, []int{12}
}

func (m *L2RRoomUserStandup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2RRoomUserStandup.Unmarshal(m, b)
}
func (m *L2RRoomUserStandup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2RRoomUserStandup.Marshal(b, m, deterministic)
}
func (m *L2RRoomUserStandup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2RRoomUserStandup.Merge(m, src)
}
func (m *L2RRoomUserStandup) XXX_Size() int {
	return xxx_messageInfo_L2RRoomUserStandup.Size(m)
}
func (m *L2RRoomUserStandup) XXX_DiscardUnknown() {
	xxx_messageInfo_L2RRoomUserStandup.DiscardUnknown(m)
}

var xxx_messageInfo_L2RRoomUserStandup proto.InternalMessageInfo

func (m *L2RRoomUserStandup) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func init() {
	proto.RegisterType((*S2LRoomUserEnter)(nil), "pt_logical.s2l_room_user_enter")
	proto.RegisterType((*L2SRoomUserEnterResult)(nil), "pt_logical.l2s_room_user_enter_result")
	proto.RegisterMapType((map[uint32]*pt_com.RoomTableItem)(nil), "pt_logical.l2s_room_user_enter_result.TablesEntry")
	proto.RegisterMapType((map[uint64]*pt_com.RoomUserItem)(nil), "pt_logical.l2s_room_user_enter_result.UsersEntry")
	proto.RegisterType((*S2LRoomUserLeave)(nil), "pt_logical.s2l_room_user_leave")
	proto.RegisterType((*L2SRoomUserLeaveResult)(nil), "pt_logical.l2s_room_user_leave_result")
	proto.RegisterType((*L2SRoomNotifyAppendUser)(nil), "pt_logical.l2s_room_notify_append_user")
	proto.RegisterType((*L2SRoomNotifyRemoveUser)(nil), "pt_logical.l2s_room_notify_remove_user")
	proto.RegisterType((*R2LTableLogin)(nil), "pt_logical.r2l_table_login")
	proto.RegisterType((*L2RTableLoginResult)(nil), "pt_logical.l2r_table_login_result")
	proto.RegisterType((*R2LTableLost)(nil), "pt_logical.r2l_table_lost")
	proto.RegisterType((*L2RRoomUserEnter)(nil), "pt_logical.l2r_room_user_enter")
	proto.RegisterType((*L2RRoomUserLeave)(nil), "pt_logical.l2r_room_user_leave")
	proto.RegisterType((*L2RRoomUserSitdown)(nil), "pt_logical.l2r_room_user_sitdown")
	proto.RegisterType((*L2RRoomUserStandup)(nil), "pt_logical.l2r_room_user_standup")
}

func init() { proto.RegisterFile("pt_logical/room.proto", fileDescriptor_ddbfd73fe07213aa) }

var fileDescriptor_ddbfd73fe07213aa = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x9a, 0xb4, 0x88, 0xa9, 0x16, 0x90, 0xab, 0x2d, 0x51, 0xb9, 0x54, 0x3e, 0x55, 0x0b,
	0x9b, 0x8a, 0x70, 0x00, 0x71, 0x47, 0x48, 0x5c, 0x40, 0x16, 0x88, 0x63, 0x94, 0x4d, 0x0c, 0x84,
	0x3a, 0x71, 0x64, 0xbb, 0x45, 0xe5, 0x3d, 0x78, 0x04, 0xde, 0x13, 0xd9, 0x4e, 0x88, 0x93, 0xd2,
	0xdd, 0x5c, 0xb8, 0x65, 0xdc, 0xf9, 0x7e, 0x66, 0x3e, 0xd7, 0x70, 0x59, 0xab, 0x84, 0xf1, 0xaf,
	0x45, 0x96, 0xb2, 0xad, 0xe0, 0xbc, 0x8c, 0x6a, 0xc1, 0x15, 0x47, 0xd0, 0x1d, 0xaf, 0x16, 0xb5,
	0x4a, 0x32, 0x5e, 0x6e, 0x33, 0x5e, 0x96, 0xbc, 0xb2, 0x0d, 0xf8, 0x3d, 0x2c, 0x64, 0xcc, 0x12,
	0x0d, 0x49, 0xf6, 0x92, 0x8a, 0x84, 0x56, 0x8a, 0x0a, 0xb4, 0x86, 0xb9, 0x86, 0x55, 0x92, 0x67,
	0x3b, 0xaa, 0x42, 0x6f, 0xed, 0x6d, 0x2e, 0x88, 0x7b, 0x84, 0x96, 0x30, 0xd3, 0xa0, 0x22, 0x0f,
	0x27, 0x6b, 0x6f, 0x13, 0x90, 0xa6, 0xc2, 0xbf, 0x7d, 0x58, 0xb1, 0x58, 0x0e, 0x19, 0x13, 0x41,
	0xe5, 0x9e, 0xa9, 0x11, 0xc4, 0x08, 0x82, 0x8c, 0xe7, 0xd4, 0xd0, 0x4e, 0x89, 0xf9, 0x76, 0xc4,
	0x7c, 0x57, 0x0c, 0xbd, 0x85, 0xa9, 0x96, 0x90, 0x61, 0xb0, 0xf6, 0x37, 0xf3, 0xf8, 0x79, 0xd4,
	0x8d, 0x1b, 0x9d, 0x37, 0x11, 0x7d, 0xd2, 0x98, 0x37, 0x95, 0x12, 0x47, 0x62, 0xf1, 0xe8, 0x1d,
	0xcc, 0x54, 0x7a, 0xc3, 0xa8, 0x0c, 0xa7, 0x86, 0x29, 0x1e, 0xc9, 0xf4, 0xd1, 0x80, 0x2c, 0x55,
	0xc3, 0xb0, 0xfa, 0x00, 0xd0, 0x09, 0xa0, 0x47, 0xe0, 0xef, 0xe8, 0xd1, 0x0c, 0x1a, 0x10, 0xfd,
	0x89, 0x9e, 0xc1, 0xf4, 0x90, 0xb2, 0xbd, 0x9d, 0x70, 0x1e, 0x2f, 0x23, 0x9b, 0x4b, 0xd4, 0x49,
	0x14, 0x8a, 0x96, 0xc4, 0x36, 0xbd, 0x9e, 0xbc, 0xf2, 0x56, 0x04, 0xe6, 0x8e, 0x90, 0x4b, 0x79,
	0x61, 0x29, 0xaf, 0xfb, 0x94, 0x8f, 0x7b, 0x94, 0xc6, 0xd6, 0x90, 0x13, 0xbf, 0x1c, 0x06, 0xcf,
	0x68, 0x7a, 0xa0, 0x77, 0xe7, 0x83, 0xbf, 0x0f, 0xf3, 0x35, 0xc0, 0xff, 0x92, 0x2f, 0xde, 0xc1,
	0x93, 0xbf, 0x5a, 0x15, 0x57, 0xc5, 0x97, 0x63, 0x92, 0xd6, 0x35, 0xad, 0x72, 0xa3, 0x3c, 0x42,
	0xec, 0x0a, 0x02, 0x3d, 0xf8, 0x1d, 0xab, 0x36, 0x3d, 0xf8, 0xf3, 0xa9, 0x98, 0xa0, 0x25, 0x3f,
	0xd0, 0xb1, 0x62, 0x4b, 0x98, 0xe9, 0xce, 0xee, 0x2f, 0x61, 0x2b, 0xfc, 0x13, 0x1e, 0x8a, 0x98,
	0x35, 0x39, 0x18, 0x80, 0x26, 0xb3, 0xb7, 0xa5, 0x47, 0xe6, 0x1c, 0xa1, 0x10, 0xee, 0xa5, 0x79,
	0x2e, 0xa8, 0x94, 0x86, 0xed, 0x3e, 0x69, 0x4b, 0xf4, 0xb4, 0x99, 0xc9, 0xbf, 0x3d, 0x6b, 0x3b,
	0xd4, 0x2f, 0x0f, 0x96, 0x2c, 0x16, 0xae, 0x78, 0x1b, 0x55, 0x1b, 0x84, 0xe7, 0x04, 0x31, 0xf0,
	0x35, 0xb9, 0xd5, 0x97, 0xff, 0x6f, 0x5f, 0xc1, 0x18, 0x5f, 0x57, 0xf0, 0xc0, 0xdd, 0x89, 0x34,
	0xc4, 0xa6, 0x2a, 0xf2, 0x66, 0x1d, 0x6d, 0x89, 0xaf, 0x61, 0xa1, 0x47, 0x18, 0xbe, 0x51, 0xdd,
	0xba, 0xbd, 0xde, 0xba, 0x4f, 0xda, 0xed, 0xcd, 0x3e, 0xd7, 0x9e, 0xc1, 0x65, 0xbf, 0x5d, 0x16,
	0x2a, 0xe7, 0x3f, 0xaa, 0x73, 0x00, 0xd7, 0xe8, 0xa4, 0x67, 0x54, 0xff, 0x92, 0x7d, 0x4b, 0x0b,
	0xd1, 0xdc, 0xe3, 0x0b, 0xd2, 0x96, 0x78, 0x7b, 0x22, 0xa2, 0xd2, 0x2a, 0xdf, 0xd7, 0xe7, 0x44,
	0x6e, 0x66, 0xe6, 0x79, 0x7e, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xa0, 0x26, 0xd7, 0xd8,
	0x05, 0x00, 0x00,
}
