// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pt_database/login.proto

package pt_database

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type L2DLoginUser struct {
	Logicalsocket        uint32   `protobuf:"varint,1,opt,name=logicalsocket,proto3" json:"logicalsocket,omitempty"`
	Loginsocket          uint32   `protobuf:"varint,2,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2DLoginUser) Reset()         { *m = L2DLoginUser{} }
func (m *L2DLoginUser) String() string { return proto.CompactTextString(m) }
func (*L2DLoginUser) ProtoMessage()    {}
func (*L2DLoginUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf0f1609ecae2d0, []int{0}
}

func (m *L2DLoginUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2DLoginUser.Unmarshal(m, b)
}
func (m *L2DLoginUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2DLoginUser.Marshal(b, m, deterministic)
}
func (m *L2DLoginUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2DLoginUser.Merge(m, src)
}
func (m *L2DLoginUser) XXX_Size() int {
	return xxx_messageInfo_L2DLoginUser.Size(m)
}
func (m *L2DLoginUser) XXX_DiscardUnknown() {
	xxx_messageInfo_L2DLoginUser.DiscardUnknown(m)
}

var xxx_messageInfo_L2DLoginUser proto.InternalMessageInfo

func (m *L2DLoginUser) GetLogicalsocket() uint32 {
	if m != nil {
		return m.Logicalsocket
	}
	return 0
}

func (m *L2DLoginUser) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *L2DLoginUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *L2DLoginUser) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *L2DLoginUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type D2LLoginUserResult struct {
	Logicalsocket        uint32   `protobuf:"varint,1,opt,name=logicalsocket,proto3" json:"logicalsocket,omitempty"`
	Loginsocket          uint32   `protobuf:"varint,2,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Userid               uint64   `protobuf:"varint,5,opt,name=userid,proto3" json:"userid,omitempty"`
	Account              string   `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Gold                 uint64   `protobuf:"varint,8,opt,name=gold,proto3" json:"gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *D2LLoginUserResult) Reset()         { *m = D2LLoginUserResult{} }
func (m *D2LLoginUserResult) String() string { return proto.CompactTextString(m) }
func (*D2LLoginUserResult) ProtoMessage()    {}
func (*D2LLoginUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf0f1609ecae2d0, []int{1}
}

func (m *D2LLoginUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_D2LLoginUserResult.Unmarshal(m, b)
}
func (m *D2LLoginUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_D2LLoginUserResult.Marshal(b, m, deterministic)
}
func (m *D2LLoginUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_D2LLoginUserResult.Merge(m, src)
}
func (m *D2LLoginUserResult) XXX_Size() int {
	return xxx_messageInfo_D2LLoginUserResult.Size(m)
}
func (m *D2LLoginUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_D2LLoginUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_D2LLoginUserResult proto.InternalMessageInfo

func (m *D2LLoginUserResult) GetLogicalsocket() uint32 {
	if m != nil {
		return m.Logicalsocket
	}
	return 0
}

func (m *D2LLoginUserResult) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *D2LLoginUserResult) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *D2LLoginUserResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *D2LLoginUserResult) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *D2LLoginUserResult) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *D2LLoginUserResult) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *D2LLoginUserResult) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

type L2DUserDataSave struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Gold                 uint64   `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2DUserDataSave) Reset()         { *m = L2DUserDataSave{} }
func (m *L2DUserDataSave) String() string { return proto.CompactTextString(m) }
func (*L2DUserDataSave) ProtoMessage()    {}
func (*L2DUserDataSave) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf0f1609ecae2d0, []int{2}
}

func (m *L2DUserDataSave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2DUserDataSave.Unmarshal(m, b)
}
func (m *L2DUserDataSave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2DUserDataSave.Marshal(b, m, deterministic)
}
func (m *L2DUserDataSave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2DUserDataSave.Merge(m, src)
}
func (m *L2DUserDataSave) XXX_Size() int {
	return xxx_messageInfo_L2DUserDataSave.Size(m)
}
func (m *L2DUserDataSave) XXX_DiscardUnknown() {
	xxx_messageInfo_L2DUserDataSave.DiscardUnknown(m)
}

var xxx_messageInfo_L2DUserDataSave proto.InternalMessageInfo

func (m *L2DUserDataSave) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *L2DUserDataSave) GetGold() uint64 {
	if m != nil {
		return m.Gold
	}
	return 0
}

type L2DRegisterUser struct {
	Logicalsocket        uint32   `protobuf:"varint,1,opt,name=logicalsocket,proto3" json:"logicalsocket,omitempty"`
	Loginsocket          uint32   `protobuf:"varint,2,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *L2DRegisterUser) Reset()         { *m = L2DRegisterUser{} }
func (m *L2DRegisterUser) String() string { return proto.CompactTextString(m) }
func (*L2DRegisterUser) ProtoMessage()    {}
func (*L2DRegisterUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf0f1609ecae2d0, []int{3}
}

func (m *L2DRegisterUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_L2DRegisterUser.Unmarshal(m, b)
}
func (m *L2DRegisterUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_L2DRegisterUser.Marshal(b, m, deterministic)
}
func (m *L2DRegisterUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_L2DRegisterUser.Merge(m, src)
}
func (m *L2DRegisterUser) XXX_Size() int {
	return xxx_messageInfo_L2DRegisterUser.Size(m)
}
func (m *L2DRegisterUser) XXX_DiscardUnknown() {
	xxx_messageInfo_L2DRegisterUser.DiscardUnknown(m)
}

var xxx_messageInfo_L2DRegisterUser proto.InternalMessageInfo

func (m *L2DRegisterUser) GetLogicalsocket() uint32 {
	if m != nil {
		return m.Logicalsocket
	}
	return 0
}

func (m *L2DRegisterUser) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *L2DRegisterUser) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *L2DRegisterUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type D2LRegisterUserResult struct {
	Logicalsocket        uint32   `protobuf:"varint,1,opt,name=logicalsocket,proto3" json:"logicalsocket,omitempty"`
	Loginsocket          uint32   `protobuf:"varint,2,opt,name=loginsocket,proto3" json:"loginsocket,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *D2LRegisterUserResult) Reset()         { *m = D2LRegisterUserResult{} }
func (m *D2LRegisterUserResult) String() string { return proto.CompactTextString(m) }
func (*D2LRegisterUserResult) ProtoMessage()    {}
func (*D2LRegisterUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bf0f1609ecae2d0, []int{4}
}

func (m *D2LRegisterUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_D2LRegisterUserResult.Unmarshal(m, b)
}
func (m *D2LRegisterUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_D2LRegisterUserResult.Marshal(b, m, deterministic)
}
func (m *D2LRegisterUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_D2LRegisterUserResult.Merge(m, src)
}
func (m *D2LRegisterUserResult) XXX_Size() int {
	return xxx_messageInfo_D2LRegisterUserResult.Size(m)
}
func (m *D2LRegisterUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_D2LRegisterUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_D2LRegisterUserResult proto.InternalMessageInfo

func (m *D2LRegisterUserResult) GetLogicalsocket() uint32 {
	if m != nil {
		return m.Logicalsocket
	}
	return 0
}

func (m *D2LRegisterUserResult) GetLoginsocket() uint32 {
	if m != nil {
		return m.Loginsocket
	}
	return 0
}

func (m *D2LRegisterUserResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *D2LRegisterUserResult) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *D2LRegisterUserResult) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*L2DLoginUser)(nil), "pt_database.l2d_login_user")
	proto.RegisterType((*D2LLoginUserResult)(nil), "pt_database.d2l_login_user_result")
	proto.RegisterType((*L2DUserDataSave)(nil), "pt_database.l2d_user_data_save")
	proto.RegisterType((*L2DRegisterUser)(nil), "pt_database.l2d_register_user")
	proto.RegisterType((*D2LRegisterUserResult)(nil), "pt_database.d2l_register_user_result")
}

func init() { proto.RegisterFile("pt_database/login.proto", fileDescriptor_3bf0f1609ecae2d0) }

var fileDescriptor_3bf0f1609ecae2d0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xc9, 0xd6, 0x75, 0xf3, 0x8c, 0x09, 0x06, 0xd4, 0xe0, 0x55, 0x29, 0x5e, 0xec, 0x4a,
	0x61, 0xbe, 0x80, 0xcf, 0xd0, 0x17, 0x28, 0x59, 0x12, 0x4a, 0x31, 0x2c, 0x25, 0x27, 0xd5, 0xe7,
	0xf0, 0x2d, 0xbc, 0xf0, 0xdd, 0x7c, 0x05, 0xc9, 0x59, 0x2b, 0xa9, 0xb0, 0x1b, 0x19, 0xde, 0xe5,
	0xcf, 0x39, 0x3d, 0xe7, 0xff, 0xf9, 0x1a, 0xb8, 0xed, 0x42, 0xad, 0x65, 0x90, 0x7b, 0x89, 0xe6,
	0xd1, 0xba, 0xa6, 0x3d, 0x3c, 0x74, 0xde, 0x05, 0xc7, 0xd7, 0x49, 0xa1, 0xfc, 0x60, 0x70, 0x69,
	0x77, 0xba, 0xa6, 0x86, 0xba, 0x47, 0xe3, 0xf9, 0x3d, 0x6c, 0xa2, 0x52, 0xd2, 0xa2, 0x53, 0x2f,
	0x26, 0x08, 0x56, 0xb0, 0xed, 0xa6, 0x9a, 0x5e, 0xf2, 0x02, 0xd6, 0xf4, 0xcd, 0xd0, 0x33, 0xa3,
	0x9e, 0xf4, 0x8a, 0x0b, 0x58, 0x4a, 0xad, 0xbd, 0x41, 0x14, 0xf3, 0x82, 0x6d, 0x2f, 0xaa, 0x51,
	0x52, 0x45, 0x29, 0xd7, 0x1f, 0x82, 0xc8, 0x86, 0xca, 0x51, 0xf2, 0x3b, 0x58, 0x75, 0x12, 0xf1,
	0xcd, 0x79, 0x2d, 0x16, 0x54, 0xfa, 0xd1, 0xe5, 0x17, 0x83, 0x6b, 0xbd, 0xb3, 0x89, 0xd5, 0xda,
	0x1b, 0xec, 0x6d, 0xf8, 0x07, 0xc7, 0x1c, 0x32, 0xe5, 0xb4, 0x21, 0xbb, 0x8b, 0x8a, 0xce, 0xfc,
	0x06, 0xf2, 0x68, 0xa2, 0x3d, 0x3a, 0xcd, 0xaa, 0x41, 0xa5, 0xe9, 0xf2, 0xd3, 0xe9, 0x96, 0xd3,
	0x74, 0x71, 0x43, 0xe3, 0xac, 0x16, 0x2b, 0x9a, 0x45, 0xe7, 0xf2, 0x19, 0x78, 0x64, 0x43, 0x51,
	0x23, 0xb1, 0x1a, 0xe5, 0x6b, 0xba, 0x97, 0x4d, 0xf6, 0x8e, 0x13, 0x66, 0xc9, 0x84, 0x77, 0x06,
	0x57, 0x71, 0x84, 0x37, 0x4d, 0x8b, 0xc1, 0xf8, 0xf3, 0x13, 0x1e, 0x92, 0xce, 0x4f, 0x27, 0xcd,
	0x7e, 0x71, 0xfc, 0x64, 0x20, 0x22, 0xc7, 0x89, 0xa7, 0x73, 0xa3, 0x1c, 0x81, 0xcd, 0x13, 0x60,
	0x7f, 0xfa, 0xed, 0xf6, 0x39, 0xbd, 0x9a, 0xa7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xd5,
	0xc7, 0x12, 0x50, 0x03, 0x00, 0x00,
}
